server:
  port: 8090
  servlet:
    context-path: /cms-master

spring:
  datasource:
    url: jdbc:mariadb://115.146.122.211:3306/cms_master
    username: el-course
    password: 123456aA
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    format:
      date: dd/MM/yyyy HH:mm:ss

ngs:
  clients:
    vinh-phuc:
      url: http://localhost:8090/cms-master
    thai-nguyen:
      url: http://localhost:8090/cms-master
    hai-duong:
      url: http://localhost:8090/cms-master
    long-an:
      url: http://localhost:8090/cms-master
